Support serializing Message
thunderbird/ews-rs pull request #10
Opened 2024-05-15 11:19 UTC by babolivier

Prerequisite to support sending messages, since [`CreateItem`](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/createitem-operation-email-message) uses the same `Message` type as `GetItem`. Note that this makes `Message::item_id` an `Option`, since we don't have an Exchange ID when sending.

Requires https://github.com/thunderbird/xml-struct-rs/pull/7, https://github.com/thunderbird/xml-struct-rs/pull/8

2024-05-15 12:07 UTC, babolivier commented
I realise I haven't correctly figured out namespaces here. From what I can tell from the CreateItem [example](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/createitem-operation-email-message), everything under `Items` needs to be under the "types" namespace. I can see two ways to make this happen:

1. decorate every field and "sub-field" of an item with `#[xml_struct(ns_prefix = "t")]`
2. set the default namespace for `RealItem` to `TYPES_NS_URI`

I'm more inclined towards option 2, because it's way less boilerplatey, but I don't know what side-effects it would have on types we depend on several level deep. Thoughts?

2024-05-15 15:26 UTC, leftmostcat commented
Is `variant_ns_prefix` (https://github.com/thunderbird/xml-struct-rs/blob/ace285b5848750064d4f5ad30ddc0c0bff53d8a9/xml_struct_derive/src/lib.rs#L162) helpful?

2024-05-15 15:31 UTC, babolivier commented
> Is `variant_ns_prefix` (https://github.com/thunderbird/xml-struct-rs/blob/ace285b5848750064d4f5ad30ddc0c0bff53d8a9/xml_struct_derive/src/lib.rs#L162) helpful?

Not in this case, because it doesn't trickle down to the types nested inside the enum variant (i.e. setting it on `RealItem` only sets the prefix on the `Message` tag, not e.g. `MimeContent`.

I think the solution above should do the trick, in which case I'll PR it along with the structures for `CreateItem`.

2024-05-22 18:47 UTC, leftmostcat requested changes

2024-05-22 18:47 UTC, leftmostcat commented on src/types/common.rs
> +    /// innder [`time::OffsetDateTime`] to an ISO 8601 compliant string.
nitpick: Rust function docs generally use present indicative rather than imperative. "a `DateTime`" is more consistent with `xml_struct` docs. Everything else is just editing.

```suggestion
    /// Serializes a `DateTime` as an XML text content node by formatting the
    /// inner [`time::OffsetDateTime`] as an ISO 8601-compliant string.
```

2024-05-22 18:47 UTC, leftmostcat commented on src/types/common.rs
>  pub enum RoutingType {
issue: Needs `#[xml_struct(text)]`.

2024-05-22 18:47 UTC, leftmostcat commented on src/types/common.rs
>  pub enum MailboxType {
issue: Needs `#[xml_struct(text)]`.

2024-05-22 18:47 UTC, leftmostcat commented on src/types/common.rs
>  pub enum Importance {
issue: Needs `#[xml_struct(text)]`.

2024-05-22 18:47 UTC, leftmostcat commented on src/types/common.rs
>  pub enum Sensitivity {
issue: Needs `#[xml_struct(text)]`.

2024-05-22 18:48 UTC, leftmostcat commented
In addition to the needed changes listed, I don't see changes here to address the namespacing issue.

2024-05-23 08:58 UTC, babolivier commented
> In addition to the needed changes listed, I don't see changes here to address the namespacing issue.

Yeah, as I mentioned in my previous comment the solution I have in mind is to decorate the `Items` struct used by `CreateItem` with `#[xml_struct(default_ns = TYPES_NS_URI)]`, which I believe should remove the need for setting a namespace prefix for each field and field's field. I'm planning on PR'ing that change separately, along with the `CreateItem` struct.

2024-05-23 09:09 UTC, babolivier commented on src/types/common.rs
>  pub enum RoutingType {
```suggestion
#[xml_struct(text)]
pub enum RoutingType {
```

2024-05-23 09:09 UTC, babolivier commented on src/types/common.rs
>  pub enum MailboxType {
```suggestion
#[xml_struct(text)]
pub enum MailboxType {
```

2024-05-23 09:09 UTC, babolivier commented on src/types/common.rs
>  pub enum Importance {
```suggestion
#[xml_struct(text)]
pub enum Importance {
```

2024-05-23 09:09 UTC, babolivier commented on src/types/common.rs
>  pub enum Sensitivity {
```suggestion
#[xml_struct(text)]
pub enum Sensitivity {
```

2024-05-23 16:48 UTC, leftmostcat approved these changes

2024-05-23 16:50 UTC, merged