Add types for CreateItem
thunderbird/ews-rs pull request #11
Opened 2024-05-24 11:14 UTC by babolivier

2024-05-24 11:19 UTC, babolivier commented on src/types/common.rs
> +#[derive(Clone, Debug, Deserialize, XmlSerialize)]
This is a bit that was forgotten in https://github.com/thunderbird/ews-rs/pull/10, see https://phabricator.services.mozilla.com/D211258

2024-05-24 11:19 UTC, babolivier commented on src/types/common.rs
> +    #[xml_struct(ns_prefix = "t")]
As per discussion on Matrix, it looks like EWS doesn't correctly supports default namespaces when they're on an element that's nested under another one that already has a default namespace. This means we cannot simply set the default namespace of the `Items` tag to be `TYPES_NS_URI`, but we instead need to only set the `t:` prefix for each tag nested underneath it.

I've decided to only add it to the elements we will initially use here, but happy to add it to every element under `Message` if that's more desirable.

2024-05-24 11:19 UTC, babolivier commented on src/types/create_item.rs
> +pub struct CreateItemResponseResponseMessage {
This has the exact same structure as `GetItemResponseMessage`, so I'm wondering whether to move it to `commons.rs`.

2024-06-05 15:07 UTC, babolivier commented on src/types/common.rs
> +#[derive(Clone, Debug, Deserialize, XmlSerialize)]
Actually this is not necessary.

2024-06-06 18:50 UTC, leftmostcat requested changes
No huge or structural changes here, mostly naming and documentation, but a few of those I think are important enough to merit blocking.

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +    #[xml_struct(ns_prefix = "t")]
suggestion: I feel like we should probably serialize correctly regardless of what consumers of the crate provide. Even though we're the only expected consumer right now, we should avoid making assumptions that only fit our needs if we can do so without significant effort (even if it's annoying effort).

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +    #[serde(default)]
nitpick: I think it's more readable if we have a blank line before field attributes.

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +    pub to_recipients: Option<Vec<Recipient>>,
suggestion: Since these attributes are being repeated on several fields of the same type, can we newtype it? Does that still produce correct results?

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +/// mean using different models to represent a single vs multiple recipient(s).
todo:
- Use conventional present indicative.
- Separate discussion of usage caveats, design considerations, etc. into a new paragraph. In part, it's easier to tell at a glance which part of the docstring is the short summary; in part, the docs generation tool gives special priority to the first paragraph as a short summary when listing top-level items.
- Use backticks around types. My preference is to also use them around crate names, less sure about the conventionality of that.

```suggestion
/// Deserializes a list of recipients.
///
/// `quick-xml`'s `serde` implementation requires the presence of an
/// intermediate type when dealing with lists, and this is not compatible with
/// our model for serialization.
/// 
/// We could directly deserialize into a `Vec<Mailbox>`, which would also
/// simplify this function a bit, but this would mean using different models
/// to represent single vs. multiple recipient(s).
```

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +    struct MailboxSequence {
nitpick: I'd prefer to use `ArrayOfRecipients` here, in keeping with EWS naming, but it's less of a concern for a private type.

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +            })
suggestion: Use `into_iter()` and avoid the `clone()`.

2024-06-06 18:50 UTC, leftmostcat commented on src/types/common.rs
> +#[derive(Clone, Debug, Deserialize, XmlSerialize)]
thought: The `Clone` isn't necessary here, but the API guidelines _do_ suggest that we eagerly implement common traits, so we probably ought to keep it. Probably ought to expand implementing it, even, but that's a different PR.

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +    /// The item(s) to create.
nitpick: I just like being a bit more speech-like about this in technical writing. Maybe this is just a localization habit.

```suggestion
    /// The item or items to create.
```

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +/// item.
suggestion: This is a little clearer about what actually happens, I think.

```suggestion
/// The action an Exchange server will take upon creating a `Message` item.
```

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +    /// message item.
```suggestion
    /// The action the Exchange server will take upon creating this item.
    ///
    /// This field is required for and only applicable to [`Message`] items.
    ///
    /// [`Message`]: `crate::Message`
```

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +    pub message_disposition: MessageDisposition,
todo: Make this an `Option`. It's required now, but won't be when we add calendar items. We might as well future-proof.

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +    /// message item.
todo: EWS docs suggest this isn't only applicable to `Message`s.

nitpick: I generally prefer to avoid contractions in technical writing.

```suggestion
    /// The folder in which to store an item once it has been created.
```

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +    /// See <https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/saveditemfolderid>
todo: Use backticks around type names.

suggestion: May as well reference the field directly since it's part of this same struct. Linking seems less important, but is always nice.

```suggestion
    /// This is ignored if `message_disposition` is [`SendOnly`].
    ///
    /// See <https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/saveditemfolderid>
    ///
    /// [`SendOnly`]: [`MessageDisposition::SendOnly`]
```

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +pub struct CreateItemResponseResponseMessage {
typo: `CreateItemResponseResponseMessage` -> `CreateItemResponseMessage`

2024-06-06 18:50 UTC, leftmostcat commented on src/types/create_item.rs
> +pub struct CreateItemResponseResponseMessage {
I think I'd prefer to keep this as a separate type, largely for semantic reasons. Each operation has its own defined request and response types, which makes it clear where to find those types, where those types belong, and what the correct procedure is to define a new one. It also keeps us aligned with EWS's schema definitions and, if we move to generation from the schema definitions, we'd have that separation again anyhow.

As a general practice, I also think it's best to keep separate types when encoding a service which treats them as different types. We're pretty sure at this point that Microsoft won't _actually_ change either of these types, but if EWS were still an API under active development and they said "this is one type and this is another", we'd want to avoid a situation where had to have a breaking API change because they changed something in one and not the other and we need to adapt.

2024-06-10 17:22 UTC, babolivier commented on src/types/common.rs
> +    struct MailboxSequence {
I'm naming the public newtype for `Vec<Recipient>` as `ArrayOfRecipients`, and I feel like it would be confusing (even though correct) to shadow it here.

2024-06-10 17:22 UTC, babolivier commented on src/types/create_item.rs
> +    pub message_disposition: MessageDisposition,
Oh good point, I hadn't realised it was only required for messages. Thanks for pointing it out!

2024-06-10 17:22 UTC, babolivier commented on src/types/create_item.rs
> +pub struct CreateItemResponseResponseMessage {
Damn, I knew that name was suspiciously long.

2024-06-10 17:22 UTC, babolivier commented on src/types/create_item.rs
> +pub struct CreateItemResponseResponseMessage {
Good points.

2024-06-10 18:05 UTC, babolivier commented on src/types/common.rs
> +    pub to_recipients: Option<Vec<Recipient>>,
I've newtype'd it, and I've added tests to ensure/confirm it still works as expected.

2024-06-17 14:46 UTC, babolivier commented
Following our discussion from last week, I've updated this PR to include a `Message` type specific to `CreateItem`.

2024-06-20 12:01 UTC, ikeycode requested changes
minor changes requested, once addressed then a LGTM.

2024-06-20 12:01 UTC, ikeycode commented on src/types/common.rs
> +            recipients.0[0],
Per matrix convo I'd prefer that we forward `Vec<T>::get` and `Vec<T>::get_mut` for `Option<T>`, as an agreed simpler path than implementing Deref etc, while retaining safety and clean code.

2024-06-20 12:01 UTC, ikeycode commented on src/types/create_item.rs
> +pub enum Item {
I think it's worth either having the unsupported commented out fields here or recording the fact the enum will grow in time. For sanity sake *may* be worth considering `non_exhaustive` ?

2024-06-20 15:07 UTC, babolivier commented on src/types/create_item.rs
> +pub enum Item {
Good point, I'll also mark `common::Item` as `non_exhaustive`.

2024-06-20 15:41 UTC, babolivier commented on src/types/common.rs
> +            recipients.0[0],
Actually, going back on `get`/`get_mut` vs `Deref`/`DerefMut`, it turns out it's easier (and possibly makes more sense semantically) to implement these traits than forward the methods while retaining the correct signature. 

Plus there are other methods from `Vec` we might want to use, e.g. `ews_xpcom` uses `.0.iter()` (https://phabricator.services.mozilla.com/D212838), and going back and forwarding every new method we want to use on the `Vec` sounds cumbersome (since all `ArrayOfRecipients` is, is a wrapper over the `Vec` to reduce boilerplate coming from `serde`).

So I've implemented `Deref` and `DerefMut` instead.

2024-06-20 17:44 UTC, ikeycode commented on src/types/common.rs
> +            recipients.0[0],
Ooh beautiful.

2024-06-20 17:45 UTC, ikeycode commented on src/types/common.rs
> +impl Deref for ArrayOfRecipients {
Yeah this does seem a lot cleaner tbqh 👍🏻

2024-06-20 17:45 UTC, ikeycode approved these changes
Thanks for incorporating the feedback, very nicely done!

2024-06-20 17:47 UTC, merged