Created UpdateItem and added necessary trait implementations
thunderbird/ews-rs pull request #18
Opened 2024-10-23 14:25 UTC by tobypilling

I put this together for mark read/unread - can you let me know if you would have approached it differently?

I tried to follow create_item and get_item but wasn't sure how much I should be adjusting common.rs vs keeping things local to update_item.rs

Can you maybe give some guidance?

2024-10-23 14:32 UTC, babolivier commented on src/types/common.rs
> +}
Unless we're dealing with a particularly complex type, `Default` implementations should usually be derived via the `derive(...)` attribute of the related type (`Message`, in this case), rather than implemented explicitly like here.

2024-10-23 14:34 UTC, babolivier commented on src/types/update_item.rs
> +    /// See <https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/itemshape>
I think this should be https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/updateitem#messagedisposition-attribute instead

2024-10-23 14:35 UTC, babolivier commented on src/types/update_item.rs
> +    pub conflict_resolution: ConflictResolution,
Since this is an XML attribute, it should have the `#[xml_struct(attribute)]` attribute, so the serialization code knows how to serialize it correctly.

2024-10-23 14:35 UTC, babolivier commented on src/types/update_item.rs
> +use crate::types::common::{BaseItemId, Updates, ItemChange, ItemChanges, ConflictResolution, MessageDisposition, PathToElement, Importance};
This file is missing a license header.

2024-10-23 14:41 UTC, babolivier commented on src/types/update_item.rs
> +}
At the moment, we generally limit the code in ews-rs only to types that represent EWS operations and the structures they contain. There are a few functions/methods here and there, but they only contain serialization logic to help translate the types into/from XML.

Another issue is that we might want to update more item properties in the future, and constantly adding new `new_...` methods to this file is not really sustainable.

I think it'd be best to leave these out, and implement the construction of struct instances to the consumer - in our case ews_xpcom.

2024-10-23 14:43 UTC, babolivier commented on src/types/update_item.rs
> +/// See <https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/updateitem>
The documentation page for `UpdateItemResponse` seems to be https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/updateitemresponse

2024-10-23 14:48 UTC, babolivier commented on src/types/update_item.rs
> +    pub message_disposition: MessageDisposition,
I think this should be `Option<MessageDisposition>` considering it's not required for non-message items.

2024-10-23 14:51 UTC, babolivier commented on src/types/common.rs
> +/// Represents a change to an individual item, including the item ID and updates.
Please include a link to the documentation page for each struct that implements a matching EWS structure, e.g.:

```
/// Represents a change to an individual item, including the item ID and updates.
///
/// See <https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/itemchange>

2024-10-23 14:52 UTC, babolivier commented on src/types/common.rs
> +}
I think this struct should be moved to `update_item.rs` since it's specific to `UpdateItem`.

2024-10-23 14:55 UTC, babolivier commented on src/types/common.rs
> +    #[serde(rename = "t:ItemId")]
I don't think serde renames are necessary. quick-xml (which is the flavour of serde we use under the hood) should be able to translate the XML tag names to the struct names in most cases.

2024-10-23 14:55 UTC, babolivier commented on src/types/common.rs
> +}
Are these structs specific to `UpdateItem`? If so they should reside in `update_item.rs`.

2024-10-23 14:57 UTC, babolivier commented on src/types/common.rs
> +/// This struct contains details of the field that needs to be updated (in this case, marking a message as read/unread).
> (in this case, marking a message as read/unread)

I'd recommend not tying a struct to a specific action if we're likely to reuse it for something else in another feature.

2024-10-23 15:43 UTC, leftmostcat commented on src/types/update_item.rs
> +}
It may be that at some point we want to add API to make it easier to handle these structures or call the operations, but we don't have enough experience with how we use them or how we might want to use them to even really have a good discussion around it. As Brendan said, we should probably only add functions when something we know we need to do often is particularly cumbersome.

2024-10-23 15:45 UTC, leftmostcat commented on src/types/common.rs
> +#[derive(Debug, Deserialize, XmlSerialize)]
question: Is there a need to add these `Deserialize` and `XmlSerialize` derivations? In many cases, we will never need to read/write some structures.

2024-10-23 15:55 UTC, leftmostcat commented on src/types/common.rs
> +/// Identifies the type of conflict resolution to try during an update. The default value is AutoResolve.
nitpick: Convention in Rust documentation is to use a noun phrase when documenting type definitions or fields and indicative verb phrases for functions. They should also be limited to 80 columns where possible.

todo: We should not copy-paste the documentation directly from Microsoft in general. In part, it places additional license burdens on us (they use an attribution license), and in part it often contains mistakes.

```suggestion
/// The method used by the Exchange server to resolve conflicts between item
/// updates.
```

2024-10-23 15:57 UTC, leftmostcat commented on src/types/common.rs
> +}
todo: This should be moved rather than duplicated (and so the existing copy should be removed). The documentation should also probably link to both references, since unfortunately there isn't a single generic one. Sigh.

2024-10-23 16:07 UTC, leftmostcat commented on src/types/common.rs
> +}
todo: If Microsoft's documentation reflects a default, it probably makes sense for us to represent that with the `Default` trait.
```suggestion
#[derive(Clone, Copy, Debug, Default, XmlSerialize)]
#[xml_struct(text)]
pub enum ConflictResolution {
    NeverOverwrite,

    #[default]
    AutoResolve,

    AlwaysOverwrite,
}
```

2024-10-23 16:08 UTC, leftmostcat commented on src/types/update_item.rs
> +    pub conflict_resolution: ConflictResolution,
todo: It should also be `Option`, as the docs indicate it has a default behavior.

2024-10-23 16:10 UTC, leftmostcat commented on src/types/update_item.rs
> +    type Response = UpdateItemResponse; // Define the appropriate response type if needed.
nitpick: The comment doesn't really make sense to me (the response type is needed) and I'm not in love with comments trailing a line of code anyhow.

2024-10-28 21:01 UTC, leftmostcat requested changes
I'm asking for quite a few changes here and a lot of them are about style and convention in documentation or ordering of files for consistency. Additionally, there are some slightly bigger changes that are needed because of decisions we made earlier which impact the way the `Message` struct is used. I will put up a PR into this branch to try to illustrate what I'm expecting rather than flooding this one with suggestions.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/common.rs
> +#[derive(Clone, Default, Debug, Deserialize, XmlSerialize, PartialEq)]
todo: `Default` doesn't make sense here. See next comment.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/common.rs
> +#[derive(Clone, Debug, Default, Deserialize, XmlSerialize)]
todo: Make `item_id` be `Option<ItemId>`. As it is, this won't accomplish what Exchange is expecting. For example, if you want to set just the body, `UpdateItem` would expect the following:

```xml
<Message>
  <Body>foo</Body>
</Message>
```

Presumably, to accomplish this we'd do the following in Rust:
```rs
Message {
    body: String::from("foo"),
    ..Default::default(),
}
```

However, if `ItemId` is simply defaulted with this code as-is, the result would instead be this:

```xml
<Message>
  <ItemId>
    <Id></Id>
  </ItemId>
  <Body>foo</Body>
</Message>

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +    pub updates: Updates, // Represents the <t:Updates> element containing the changes.
suggestion: I'm not a fan of this line-trailing comments, and I would generally prefer they be standard comments on the line preceding. In this case, they should be doc comments following the usual conventions. This goes for the several other occurrences throughout the file.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +/// Represents a change to an individual item, including the item ID and updates.
nitpick: This and the other struct comments throughout the file should follow the noun phrase convention.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +/// Struct representing updates to be applied to an item.
suggestion: "Struct representing" is implicit in the declaration already and doesn't really add anything here.

```suggestion
/// A list of changes to fields, with each element representing a single change.
```

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +/// This struct is used to create an UpdateItem request.
nitpick: This doesn't really add anything not implied by the type hierarchy.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +    pub set_item_field: SetItemField,
issue: A couple problems here. First is that this only allows for a single field to be changed per update and it should instead be a `Vec`. Second is that it doesn't allow for append/delete operations. That should be done by using an enum.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +/// Struct representing the field update operation.
suggestion: As below, "Struct representing" doesn't add much here, and the second paragraph could easily be folded into this one to give a more complete description, but as below, this needs additional revision.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +}
issue: There's still not really cause to have this be a separate function. The field to be changed is public, so while this provides a slight shortcut to accessing that field, it also provides limited means of interacting with it. In particular, since we generally create these operation structs all at once, `push()` isn't very useful as a way of building a list of changes. Instead, we should generally be preferring using Rust iterators and `collect()`.

2024-10-28 21:01 UTC, leftmostcat commented on src/types/update_item.rs
> +}
nitpick: I have generally kept the actual definition of the operations at the beginning of the file with operation-specific types declared below. I don't have solid reasoning for this, but it's consistent and puts the named part of the file up front.

Even nitpickier but reflected in that tendency is that, in Rust, I tend to prefer to declare a type and then declare additional types on which it depends below them, e.g.:

```rs
struct Foo {
    bar: Bar,
}

struct Bar {}
```

2024-10-29 17:48 UTC, leftmostcat requested changes

2024-10-29 17:48 UTC, leftmostcat commented on src/types/update_item.rs
> +/// A request to update properties of one or more Exchange items.
todo: Link to https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/updateitem

2024-10-29 17:53 UTC, leftmostcat approved these changes

2024-10-31 18:40 UTC, babolivier approved these changes
One minor documentation nit, otherwise lgtm :)

2024-10-31 18:40 UTC, babolivier commented on src/types/common.rs
> +/// The action an Exchange server will take upon creating a `Message` item.
```suggestion
/// The action an Exchange server will take upon creating or updating a `Message` item.
```

2024-10-31 19:19 UTC, merged