Add support for `SyncFolderItems` and partial support for `GetItem`
thunderbird/ews-rs pull request #7
Opened 2024-05-02 23:04 UTC by leftmostcat

The Item type only currently has support for Messages, so GetItem requests for non-Message items will fail during deserialization.

This is still missing a fair bit of documentation.

2024-05-07 19:43 UTC, leftmostcat commented on src/types/common.rs
> +        is_inline: Option<bool>,
Here and several other places, we should really be using a common struct and `serde(flatten)`, but I tried a version of that here and couldn't make serde happy.

2024-05-07 19:44 UTC, leftmostcat commented on src/types/common.rs
> +        // See https://github.com/tafia/quick-xml/issues/683
I put up a PR to address this issue, but it's bumping up against another issue. Talking with a maintainer in hopes of sorting it all out.

2024-05-07 20:03 UTC, leftmostcat commented
A few issues/questions for discussion/future work:

# quick-xml bug

This affects deserialization of elements which contain elements with a namespace prefix and also elements drawn from an `xs:choice` (which we try to represent as enums). Discussing the best path to a fix with the maintainer.

# Common structs with flattening

https://github.com/thunderbird/ews-rs/issues/8

# Logging versus error handling

Right now, we have a `warn` log and a `debug` log. Ultimately, it's not clear whether we should be logging here at all, and it might be beneficial to bubble up the `serde_path_to_error` error for consumers.

# File organization

Right now, there are files for each operation/response pair, which I think is reasonable. Less reasonable is how the rest of the types shake out. Most of them aren't operation-specific in any documented fashion, so relying on operation organization for these isn't reasonable. But having them all lumped into a single file isn't great either. Microsoft groups types by sub-schema, which is pretty specific to how their protocols are structured, but maybe it makes sense.

# Documentation

I mentioned this PR is missing a lot, then added a bunch more, and it's still missing a lot. There are a lot of fields here to document, and it's a lot of work, but it's also valuable to have this in generated docs. How much is enough? Do we just need to bear down and write it out? How will that play out if we want to generate a schema from WSDL/XSD?

2024-05-08 18:07 UTC, babolivier requested changes
On error handling, I think it would be beneficial to bubble up the `serde_path_to_error` to consumer. If we have already concluded that the original error is of little or no value (which we have), then the consumer is unlikely to find said value in it.

On file organisation, I do agree that we should avoid `common.rs` becoming too large. I'm not sure what would be a good structure, but if Microsoft already has one then I think it would make sense to mimic it. It's fine if it's specific to their protocol, since that's what we're implementing here.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +    // TODO: We can represent in a friendlier way with an enum, probably. A
question: Why not implement this here? It feels like the right thing to do since it could programmatically enforce the restrictions described in the `ExtendedFieldURI` spec, but there might be issues with this approach (e.g. wrt serialization) that I'm not aware of.

If this is definitely out of scope for this PR, please open an issue so we can keep track of this potential improvement.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +        // TODO: We could use an enum for this field. It's just large and not
nitpick: sounds more like a "note" than a "todo" to me.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +        // TODO: Adjust xml_struct to support field renaming to avoid non-snake
suggestion: turn this into a tracking issue on the relevant repo.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +        field_URI: String,
nitpick: does `URI` need to be capitalised (for serialization purposes)?

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +pub enum PathToElement {
thought: this name feels weird, especially when compared to the enum's documentation and variant names. Maybe `FieldIdentifier` would be a more fitting name?

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +    // RecurringMasterItemId { .. }
thought: feels like these either need removing or a todo comment to contextualise them.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +    // MeetingCancellation(MeetingCancellation),
thought: same comment as prior regarding commented out variants.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +pub struct Message {
thought: I'm wondering if, for those cases where we're essentially just implementing all of the documented fields from the spec, it wouldn't make sense to not try to document every field independently, but rather explicitly call out (in the struct's doc) that the semantics of each field can be found in the related spec documentation.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +pub struct SingleRecipient {
thought: "Recipient" here feels like a misnomer considering we're also using the same struct for the sender. Maybe "Correspondent"? Not a huge fan of this one either though, so feel free to go with a better idea if you've got one.

Could also be "SingleMailbox", to better represent the struct's contents.

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +pub struct ArrayOfRecipients {
suggestion: s/ArrayOf/Multiple/

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +pub enum RoutingType {
question: The spec states "If no value is provided, the default value of SMTP is used."; should this enum implement `Default` to define `SMTP` as the default value?

2024-05-08 18:07 UTC, babolivier commented on src/types/common.rs
> +    /// The content of the body.
suggestion: document why the body might not include a content.

2024-05-08 18:07 UTC, babolivier commented on src/types/get_item.rs
> +    /// The success value of the corresponding request.
suggestion: `ResponseClass` might not indicate a success, so "success value" is misleading

```suggestion
    /// The success status of the corresponding request.
```

2024-05-08 18:07 UTC, babolivier commented on src/types/get_item.rs
> +/* This Source Code Form is subject to the terms of the Mozilla Public
issue: structures in this file are missing documentation headers with links to their respective spec.

2024-05-08 18:07 UTC, babolivier commented on src/types/soap.rs
> +        // `serde_path_to_error` ensures that we can debug the
issue: unfinished comment

2024-05-08 18:07 UTC, babolivier commented on src/types/sync_folder_items.rs
> +/* This Source Code Form is subject to the terms of the Mozilla Public
issue: some of the structures in this file are missing documentation headers with links to their respective spec.

2024-05-08 18:07 UTC, babolivier commented on src/types/soap.rs
> +                log::debug!("Failed to deserialize: {err:?}");
suggestion: should we log `err.path().to_string()` instead (possibly along with the original error message)? It feels more helpful to me if we want to log to a human.

2024-05-08 18:07 UTC, babolivier commented on src/types/soap.rs
> +                return Err(err.into_inner().into());
question: Does this mean `err` is an `serde_path_to_error::Error<quick_xml::Error>`? I would have assumed the inner error was from serde.

2024-05-08 18:21 UTC, leftmostcat commented on src/types/common.rs
> +        field_URI: String,
It does, unfortunately. Right now, we can't adjust the name of the field `xml_struct` uses; it just does PascalCase. However, the element name is `FieldURI`, not `FieldUri`, so it's this or `field_u_r_i`, which is much worse.

2024-05-08 18:31 UTC, leftmostcat commented on src/types/common.rs
> +pub enum PathToElement {
It is a weird name; I chose it based on `NonEmptyArrayOfPathsToElementType`, which is the type of `AdditionalProperties`, as seen at https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/additionalproperties. Looking at the types schema, `NonEmptyArrayOfPathsToElementType` is an array of `BasePathToElementType`, an abstract type used as the basis for `PathToExceptionFieldType`, `PathToIndexedFieldType`, and `PathToUnindexedFieldType`.

I don't love Microsoft's naming here, but ultimately we need to decide on how closely we want to hew to it.

2024-05-08 18:33 UTC, leftmostcat commented on src/types/common.rs
> +pub struct Message {
Long-term, I want our docs to stand on their own and not require reference to Microsoft's wherever possible. Additionally, Microsoft's docs are lacking in a lot of semantics that I believe we can clarify.

2024-05-08 18:33 UTC, leftmostcat commented on src/types/common.rs
> +pub struct SingleRecipient {
This is another name drawn from Microsoft's type naming. There's definitely room for discussion on this.

2024-05-08 18:36 UTC, leftmostcat commented on src/types/common.rs
> +pub struct ArrayOfRecipients {
Another Microsoft convention. Implements `ArrayOfRecipientsType`.

2024-05-08 18:38 UTC, leftmostcat commented on src/types/soap.rs
> +                log::debug!("Failed to deserialize: {err:?}");
Since this is a `debug`-level log, I think our target is developers rather than end users.

2024-05-08 18:44 UTC, leftmostcat commented on src/types/soap.rs
> +                return Err(err.into_inner().into());
It's `quick_xml::DeError`. The deserializer provides its own error type and a function for serde to create errors of that type from a string.

2024-05-08 18:54 UTC, leftmostcat commented on src/types/common.rs
> +    // TODO: We can represent in a friendlier way with an enum, probably. A
This is an untagged enum, so getting serde to recognize it properly might take a bit of doing. This structure at least correctly encodes the fields, though not the semantics, and we aren't using it right now, so I didn't want to take the time to figure it out.

I cut https://github.com/thunderbird/ews-rs/issues/9 and have referenced it in this comment.

2024-05-08 19:01 UTC, leftmostcat commented on src/types/common.rs
> +        // TODO: Adjust xml_struct to support field renaming to avoid non-snake
I cut https://github.com/thunderbird/xml-struct-rs/issues/6 and referenced it in the comment.

2024-05-08 19:15 UTC, leftmostcat commented on src/types/common.rs
> +        // TODO: We could use an enum for this field. It's just large and not
Kind of a TODO in that I'd like us to generate it at some point. :shrug:

2024-05-08 19:18 UTC, leftmostcat commented on src/types/common.rs
> +    /// The content of the body.
I'm not yet clear on this. I encountered an instance of it while testing, but haven't investigated fully. I'll make sure to fill this in as I work on handling the body in TB.

2024-05-09 11:06 UTC, babolivier commented on src/types/common.rs
> +    /// The content of the body.
In this case it might be worth adding a quick note of this in the comment, e.g. "it's not clear yet why the content might be missing but it's been observed in the wild", to provide some context to the next person working with this code.

2024-05-09 11:06 UTC, babolivier commented on src/types/common.rs
> +        field_URI: String,
Yay for API inconsistency then.

2024-05-09 11:06 UTC, babolivier commented on src/types/soap.rs
> +                log::debug!("Failed to deserialize: {err:?}");
For what it's worth, as a developer, I'd rather my log tells me the human-readable error path than having to figure it out by myself from reading a debug blob. I'll be looking for the same info in both cases, but in the former we use the existing method to make the lib do the work of making the path human-readable, and in the latter I need to do this work myself.

2024-05-09 11:09 UTC, babolivier approved these changes
Looks good to me. I've got one nitpicky-ish comment that I'd like addressed before merging (so we don't lose context after this PR lands); once this is addressed feel free to merge.

2024-05-09 12:56 UTC, leftmostcat commented on src/types/soap.rs
> +                log::debug!("Failed to deserialize: {err:?}");
That's fair. My concern was that the human-readable path would lose information, but I'll test that out.

2024-05-09 13:07 UTC, merged